project_id = "latwptcvghypdopbpxfr"

[auth]
enabled = true
site_url = "https://viltb.com"
additional_redirect_urls = ["https://viltb.com"]

[functions.request-discount]
verify_jwt = false

[functions.validate-discount-code]
verify_jwt = false

[functions.create-registration-payment]
verify_jwt = false

[functions.calculate-daily-interest]
verify_jwt = false

[functions.connect-binance-account]
verify_jwt = true

[functions.send-telegram-2fa]
verify_jwt = true


[functions.send-viber-2fa]
verify_jwt = true

[functions.send-signal-2fa]
verify_jwt = true

[functions.telegram-webhook]
verify_jwt = false

[functions.telegram-bot-setup]
verify_jwt = true

[functions.send-contact-email]
verify_jwt = false