project_id = "khcelroaozkzpyxayvpj"

[functions.send-verification-code]
verify_jwt = false

[functions.verify-code]
verify_jwt = false

[functions.send-email-2fa]
verify_jwt = false

[functions.debug-email]
verify_jwt = false

[functions.verify-totp-setup]
verify_jwt = true