
project_id = "khcelroaozkzpyxayvpj"

[functions.send-verification-code]
verify_jwt = false

[functions.verify-code]
verify_jwt = false

[functions.send-email-2fa]
verify_jwt = false

[functions.debug-email]
verify_jwt = false

[functions.email-status-checker]
verify_jwt = false

[functions.create-registration-payment]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

[functions.send-registration-confirmation]
verify_jwt = false

[functions.send-payment-confirmation]
verify_jwt = false

[functions.send-notification-email]
verify_jwt = false

[functions.verify-totp-setup]
verify_jwt = true
