project_id = "latwptcvghypdopbpxfr"

[auth]
enabled = true
site_url = "https://lovable.app"
additional_redirect_urls = ["https://lovable.app", "https://latwptcvghypdopbpxfr.supabase.co", "https://viltb.com"]

[functions.request-discount]
verify_jwt = false

[functions.validate-discount-code]
verify_jwt = false

[functions.create-registration-payment]
verify_jwt = false

[functions.calculate-daily-interest]
verify_jwt = false

[functions.connect-binance-account]
verify_jwt = true

[functions.send-telegram-2fa]
verify_jwt = true

[functions.send-viber-2fa]
verify_jwt = true

[functions.send-signal-2fa]
verify_jwt = true

[functions.telegram-webhook]
verify_jwt = false

[functions.telegram-bot-setup]
verify_jwt = true

[functions.send-contact-email]
verify_jwt = false

[functions.send-newsletter]
verify_jwt = true

[functions.send-verification-code]
verify_jwt = false

[functions.subscribe-newsletter]
verify_jwt = false

[functions.unsubscribe-newsletter]
verify_jwt = false

[functions.verify-code]
verify_jwt = false

[functions.debug-mfa]
verify_jwt = false

[functions.setup-totp]
verify_jwt = true

[functions.verify-totp-login]
verify_jwt = false

[functions.verify-totp-setup]
verify_jwt = true

[functions.send-email-2fa]
verify_jwt = true

[functions.create-deposit-payment]
verify_jwt = true

[functions.create-loan-payment]
verify_jwt = true

[functions.create-withdrawal-request]
verify_jwt = true

[functions.debug-email]
verify_jwt = false

[functions.email-status-checker]
verify_jwt = false

[functions.process-deposit-payment]
verify_jwt = false

[functions.process-loan-payment]
verify_jwt = false

[functions.setup-cron-jobs]
verify_jwt = true

[functions.submit-loan-application]
verify_jwt = false