project_id = "latwptcvghypdopbpxfr"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]

[functions.request-discount]
verify_jwt = false

[functions.validate-discount-code]
verify_jwt = false

[functions.create-registration-payment]
verify_jwt = false